apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-app
  namespace: status-app
  labels:
    app: status-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: status-app
  template:
    metadata:
      labels:
        app: status-app
    spec:
      containers:
      - name: status-app
        image: status-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6001
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: status-app-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: status-app-config
              key: NODE_ENV
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/status
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/status
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      # imagePullSecrets:
      # - name: regcred
      securityContext:
        fsGroup: 1000