apiVersion: v1
kind: Service
metadata:
  name: status-app-service
  namespace: status-app
  labels:
    app: status-app
spec:
  selector:
    app: status-app
  ports:
  - protocol: TCP
    port: 6001
    targetPort: 6001
    nodePort: 30001
    name: http
  type: NodePort